### PR TITLE
Feature: Add utilities for temporal features

### PR DESCRIPTION
**Pull request by jdamp-bis**
- Add methods to extract temporal features from a DataFrame
- Add basic sklearn transformer for usage in pipeline
- Add tests

### CODE REVIEW

**Comment by dkgaraujo** [comment]
Thanks Johannes. As discussed, let's also implement the following changes please:

- we retain the basic functionality in a dedicated .py file as now, but put the transformer class in gingado.utils
- the list of temporal features selected by the user can the None (default), in which case all relevant temporal features for that frequency are returned, or a list of specific features.
  - it should throw a warning showing any valid temporal features that are not supported for the users' data, and an error for unsupported temporal features

**Comment by dkgaraujo** [comment]
Actually I noted now that the py files are in a dedicated folder, `temporal`. Let's try to keep everything contained in the root folder. All the items that are not part of the API, like the ones in `types.py`, and the `validate_and_get_freq` method can go to `internals.py`. The remainder can go to `utils.py`. Correspondingly, their documentation should be part of `utils.qmd` and `utils.html`

**Comment by jdamp-bis** [comment]
Hi @dkgaraujo,
many thanks for your feedback
I have updated the file structure according to your suggestions and also added documentation about the temporal features to 00_utils.qmd.

**Comment by dkgaraujo** [comment]
Thanks @jdamp-bis. One final thing in my review is to import the `rng` functionality in the documentation and re-render the HTML. Ideally the documentation should be executable by the user end-to-end, so it needs to know how to import `rng`.

**Comment by jdamp-bis** [comment]
Are you referring to the `rng` object? It is a [part of numpy](https://github.com/jdamp-bis/gingado/blob/feature/add-temporal-features/00_utils.qmd#L43-L44), so no import necessary.
This follows the recommended way of generating random numbers with numpy ([docs](https://numpy.org/doc/stable/reference/random/index.html)).

**Comment by dkgaraujo** [comment]
You are right, thanks. I saw it now in the `00_utils.qmd` file; missed it because `echo: false` for that cell.

**Review by dkgaraujo — APPROVED** [review]

**Pull request merged**
